spring:
  application:
    name: auth-service
  data:
    mongodb:
      uri: mongodb://mongodb:27017/microservices
#      uri: mongodb://mongo:mongo@localhost:27017/microservices
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    hostname: service-registry

server:
  port: 8082

