version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    networks:
      - my-network

  service-registry:
    image: docker-service-registry:1
    container_name: service-registry
    ports:
      - "8761:8761"
    networks:
      - my-network

  
  cloud-gateway:
    image: docker-cloud-gateway:1
    container_name: cloud-gateway
    ports:
      - "8080:8080"
    networks:
      - my-network
    depends_on:
      - service-registry
      - auth-service
      - mongodb
      - user-service

  auth-service:
    image: docker-auth-service:1
    container_name: auth-service
    ports:
      - "8082:8082"
    networks:
      - my-network
    depends_on:
      - service-registry
      - mongodb

  user-service:
    image: docker-user-service:1
    container_name: user-service
    ports:
      - "8081:8081"
    networks:
      - my-network
    depends_on:
      - service-registry

networks:
  my-network:
    driver: bridge

volumes:
  mongo-data:
