version: '3.8'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    networks:
      - my-network

  service-registry:
    image: docker-service-registry:latest
    build:
      context: ./service-registry
    ports:
      - "8761:8761"
    networks:
      - my-network

  auth-service:
    image: docker-auth-service:latest
    build:
      context: ./auth-service
    ports:
      - "8082:8082"
    networks:
      - my-network
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:mongo@mongodb:27017/auth-service
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka/
    depends_on:
      - mongodb
      - service-registry

  cloud-gateway:
    image: docker-cloud-gateway:latest
    build:
      context: ./cloud-gateway
    ports:
      - "8080:8080"
    networks:
      - my-network
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka/
    depends_on:
      - auth-service
      - service-registry

  userservice:
    image: docker-user-service:latest
    build:
      context: ./userservice
    ports:
      - "8081:8081"
    networks:
      - my-network
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka/
    depends_on:
      - auth-service
      - service-registry

networks:
  my-network:
    driver: bridge

volumes:
  mongo-data:
